Ported Link Button Demo to Vala
workbenchdev/demos pull request #131
Opened 2024-03-24 08:55 UTC by urffsamhunt

Ported the Link Button demo to Vala.

2024-03-24 17:13 UTC, Diego-Ivan requested changes

2024-03-24 17:13 UTC, Diego-Ivan commented on src/Link Button/main.vala
> +#! /usr/bin/env -S vala workbench.vala --pkg gtk4 --pkg libadwaita-1
```suggestion
#! /usr/bin/env -S vala workbench.vala --pkg gtk4
```

2024-03-24 17:13 UTC, Diego-Ivan commented on src/Link Button/main.vala
> +    linkbutton.clicked.connect (() => message ("The link has been visited"));
The signal here must be `notify["visited"]` instead of `clicked`, as in the JS demo.

2024-04-01 08:34 UTC, Hofer-Julian approved these changes
I've adapted the Rust part slightly.
At least the Rust part is good to merge from my side.

2024-04-04 01:02 UTC, Diego-Ivan requested changes

2024-04-04 01:02 UTC, Diego-Ivan commented on src/Link Button/main.vala
> +    linkbutton.clicked.connect (() => message ("The link has been visited"));
@urffsamhunt Thanks for fixing this in the Rust demo! Please make the same changes in Vala

2024-04-13 18:36 UTC, merged