Improve FileDialog entries
workbenchdev/demos pull request #64
Opened 2024-01-28 12:46 UTC by sonnyp

* Rename all references of `Gtk.FileDialog`s to `file_dialog` (`Adw.Dialog` is a thing now)
* Rename all references to `Gtk.FileFilter` to `file_filter` (conventions)
* Simplify code a bit
* Remove FileFilter name - it's never displayed
* Always use FileFilter as `default-filter`
* ... (see inline comments)

2024-01-28 17:22 UTC, Hofer-Julian approved these changes

2024-01-29 13:08 UTC, theCapypara approved these changes

2024-01-29 13:08 UTC, theCapypara commented on demos/Avatar/main.py
> +    file = file_dialog.open_finish(result)
Huh, that `_` slipped through. I really need to get that linter set up...

2024-01-30 10:44 UTC, lw64 commented on demos/Open File/main.vala
> +        }
currently not. WIP.

2024-01-30 13:05 UTC, lw64 requested changes

2024-01-30 13:05 UTC, lw64 commented on demos/Open File/main.vala
> +        var info = file.query_info ("standard::name", NONE, null);
Why not `query_info_async()` here?

2024-01-30 13:05 UTC, lw64 commented on demos/Open File/main.vala
> +        var files = yield file_dialog.open_multiple (workbench.window, null);
Is there a reason to not use `ListModel`, but `var` here?

2024-01-30 13:05 UTC, lw64 commented on demos/Open File/main.vala
> +            var file = files.get_item (i) as File;
Here a `(File)` cast please. there is no type check needed.

2024-01-30 20:09 UTC, lw64 commented on demos/Open File/main.vala
> +        var files = yield file_dialog.open_multiple (workbench.window, null);
```suggestion
        ListModel files = yield file_dialog.open_multiple (workbench.window, null);
```

2024-01-30 20:09 UTC, lw64 commented on demos/Open File/main.vala
> +            var file = files.get_item (i) as File;
```suggestion
            var file = (File) files.get_item (i);
```

2024-01-30 20:10 UTC, lw64 commented on demos/Open File/main.vala
> +        var info = file.query_info ("standard::name", NONE, null);
but `query_info` is blocking

2024-01-30 20:24 UTC, merged