Port 'WebSocket Client' demo to Python
workbenchdev/demos pull request #73
Opened 2024-02-07 16:54 UTC by rolandlo

I followed the Javascript implementation closely. It seems to work fine. I didn't find out how to provoke an error (so that `on_error` gets called).

2024-02-11 11:19 UTC, theCapypara requested changes
LGTM, except for one minor thing. Thanks!

2024-02-11 11:19 UTC, theCapypara commented on demos/WebSocket Client/main.py
> +    str = message.unref_to_array().decode("utf-8")
Please use a different name for the variable, `str` shadows the `str` type.

2024-02-11 15:32 UTC, rolandlo commented
> BTW @rolandlo you've been added to the Workbench team. You should be able to open branches directly on this repo which is a bit easier for us to checkout.
> 
> Would be great if you could do that for future PRs 🙏

Ok, I will do so in future. I was just used to always work on the fork.

2024-02-11 15:33 UTC, rolandlo commented
Thanks for all the reviews @theCapypara @sonnyp. It's really a great way of learning.

2024-02-15 18:47 UTC, theCapypara approved these changes

2024-02-19 11:25 UTC, merged